package sop_corba;


/**
* sop_corba/GestionNotificacionesOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* lunes 1 de agosto de 2022 01:47:12 AM CEST
*/

public interface GestionNotificacionesOperations 
{
  void notificaarRegistro (sop_corba.GestionNotificacionesPackage.ClsMensajeNotificacionDTO objNotificacion);
} // interface GestionNotificacionesOperations
