package sop_corba;


/**
* sop_corba/GestionNotificaciones.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from notificaciones.idl
* lunes 1 de agosto de 2022 01:47:12 AM CEST
*/

public interface GestionNotificaciones extends GestionNotificacionesOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionNotificaciones
