package sop_corba;


/**
* sop_corba/GestionPacientesPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from alertas.idl
* lunes 1 de agosto de 2022 01:46:00 AM CEST
*/

public abstract class GestionPacientesPOA extends org.omg.PortableServer.Servant
 implements sop_corba.GestionPacientesOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("registrarPaciente", new java.lang.Integer (0));
    _methods.put ("buscarPaciente", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // sop_corba/GestionPacientes/registrarPaciente
       {
         sop_corba.GestionPacientesPackage.pacienteDTO objPacienteo = sop_corba.GestionPacientesPackage.pacienteDTOHelper.read (in);
         org.omg.CORBA.BooleanHolder resultado = new org.omg.CORBA.BooleanHolder ();
         this.registrarPaciente (objPacienteo, resultado);
         out = $rh.createReply();
         out.write_boolean (resultado.value);
         break;
       }

       case 1:  // sop_corba/GestionPacientes/buscarPaciente
       {
         int numeroHabitacion = in.read_long ();
         sop_corba.GestionPacientesPackage.pacienteDTOHolder objPacienteResultado = new sop_corba.GestionPacientesPackage.pacienteDTOHolder ();
         boolean $result = false;
         $result = this.buscarPaciente (numeroHabitacion, objPacienteResultado);
         out = $rh.createReply();
         out.write_boolean ($result);
         sop_corba.GestionPacientesPackage.pacienteDTOHelper.write (out, objPacienteResultado.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/GestionPacientes:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GestionPacientes _this() 
  {
    return GestionPacientesHelper.narrow(
    super._this_object());
  }

  public GestionPacientes _this(org.omg.CORBA.ORB orb) 
  {
    return GestionPacientesHelper.narrow(
    super._this_object(orb));
  }


} // class GestionPacientesPOA
